// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use Vite env vars (project uses VITE_*), not REACT_APP_*
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Fail early with a clear error if configuration is missing
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Helpful console message during development
  console.error('[supabase] Missing environment variables: VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY');
  throw new Error('Missing Supabase env variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env');
}

// Guard localStorage usage for SSR environments where `window` is undefined
const authStorage = typeof window !== 'undefined' ? localStorage : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // supabase-js expects a storage object for client-side sessions; only set it when available
    storage: authStorage as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});